daniel155158/twitter-api-2020

.eslintignore
.eslintrc.yml
.gitattributes
package-lock.json
package.json

我先做了一些基礎設定:
(1) package.json裡的"main"改為"app.js" (原本是"index.js")
(2) package.json裡的"scripts"都補上set \"NODE_ENV=test\" && (for Windows使用)
(3) 安裝ESlint相關套件以及新增.eslintrc.yml和.eslintignore
(4) 新增.gitattributes (雖然我們目前都是用Windows開發, 但為了避免意外的衝突, 所以也先新增這個檔案)

feat: basic settings for team work (ESlint/gitattributes/package.json)

---

migrations/20190115071418-create-followship.js
migrations/20190115071419-create-like.js
migrations/20190115071420-create-reply.js
migrations/20190115071420-create-tweet.js
migrations/20190115071421-create-user.js
models/followship.js
models/like.js
models/reply.js
models/tweet.js
models/user.js

除了用ESLint除錯之外的重要變動
- migration檔案:
1. create-user: 新增account及cover, role增加defaultValue: 'user'
2. create-like: 新增deleted
- models的關聯及init設定

feat: create models (user/tweet/reply/like/followship)

---

seeders/20230320145544-users-seeder.js
seeders/20230321024041-tweets-seeder.js
seeders/20230321052647-replies-seeder.js

根據user story設計user/tweet/reply的種子資料

feat: create user/tweet/reply seeders

---

middleware/error-handler.js
routes/index.js

1. 新增error handler
2. 在route引用error handler

feat: add err-handler

---

controllers/admin-controller.js
routes/index.js
routes/modules/admin.js

新增 POST api/admin/signin 後台使用者登入

feat: add admin signin API

---

controllers/user-controller.js
routes/index.js

feat: add/remove following API

---

seeders/20230320145544-users-seeder.js

feat: user seeder update avatar/cover/introduction

---

controllers/user-controller.js
routes/index.js

feat: add getTopFollow API (most followers users)

---

controllers/admin-controller.js
controllers/user-controller.js
middleware/auth.js

fix: admin can signin 前台 and user can sigin 後台

---

controllers/admin-controller.js
routes/modules/admin.js

feat: add GET admin/users API

---

controllers/admin-controller.js
routes/modules/admin.js

feat: add DELETE admin/tweets/:id API

---

controllers/admin-controller.js
controllers/tweet-controller.js

優化項目
GET /api/tweets:
-關聯使用者的資料作簡化
-每則推文新增”回覆數” & “愛心數”
-新增period (相對時間)
-新增isLiked
GET /api/tweets/:tweet_id
-將Likes.deleted修改成isLiked
-新增period (相對時間)
POST /api/tweets/:tweet_id/replies
-反查推文是否存在
GET /api/tweets/:tweet_id/replies
-反查推文是否存在
-新增period (相對時間)
POST /api/tweets/:id/unlike
-反查推文是否存在
POST /api/admin/signin
-回傳使用者資料移除密碼/role
GET /api/admin/tweets
-時間越新的越前面 (排序)
-新增period (相對時間)
-每則推文新增”回覆數” & “愛心數”

B29 (已發PR到AC測試travis成功)

---

controllers/user-controller.js

1. 使用者登入 POST /api/users/signin  => 回傳資料移除密碼/role
2. 註冊帳號 POST /api/users => 擋下名稱超過50字的註冊
3. 瀏覽某使用者個人資料頁面 GET /api/users/:id => 回傳資料移除密碼/role
4. 看見某使用者發過的推文 GET /api/users/:id/tweets => 
刪除if (!tweet) 因為tweets會回傳空陣列故不會觸發
最新的要排前面(排序)
加period
5. 看見某使用者發過回覆的推文 GET /api/users/:id/replied_tweets =>
刪除if (!replies) 因為replies會回傳空陣列故不會觸發
最新的要排前面(排序)
加period
6.看見某使用者點過的 Like GET /api/users/:id/likes =>
刪除if (!tweet) 因為tweets會回傳空陣列故不會觸發
刪除if (!likes) 因為likes會回傳空陣列故不會觸發
刪除if (!replies) 因為replies會回傳空陣列故不會觸發
like成立的時間越新的在越前面(排序)
加period
7. 看見某使用者跟隨中的人 GET /api/users/:id/followings =>
刪除if (!users) 因為users會回傳空陣列故不會觸發
刪除if (!followings) 因為followings會回傳空陣列故不會觸發
新增反查使用者(user)是否存在
按照追蹤時間越新的在越前面(排序)
追蹤時間程式碼修正
8.看見某使用者的跟隨者 GET /api/users/:id/followers =>
刪除if (!users) 因為users會回傳空陣列故不會觸發
刪除if (!followings) …

B24 (已通過travis測試)

---

controllers/user-controller.js

註冊帳號 POST /api/users
編輯自己所有的設定 PUT /api/users/:id/setting
上述兩條路由，若account或email有與資料庫資料重複的情況發生，原先只會報錯：帳戶或email已存在。
將報錯修改得更精準：
若account重複，則提醒：account已存在。
若email重複，則提醒：email已存在。

優化(已通過travis測試)

---

controllers/user-controller.js

1. 編輯自己所有的設定 PUT /api/users/:id/setting
- attributes exclude role
2. 看見某使用者發過的推文 GET /api/users/:id/tweets
- 用資料庫幫忙計算關聯資料數(counts)
3. 看見某使用者點過的 Like GET /api/users/:id/likes
- 用資料庫幫忙計算關聯資料數(counts)
- 從資料庫直接抓取likedDate
4. 瀏覽某使用者個人資料頁面 GET /api/users/:id
- 用資料庫幫忙計算關聯資料數(counts)
- attributes exclude role & password

優化使用sequelize原生語法 (已通過travis測試)

---

controllers/admin-controller.js
controllers/tweet-controller.js
controllers/user-controller.js

**管理者可以看見站內所有的使用者 (GET /api/admin/users)**
-計算關聯資料數
-排序
**管理者可以瀏覽所有推文 (GET /api/admin/tweets)**
-計算關聯資料數
**瀏覽所有推文 (GET /api/tweets)**
-計算關聯資料數
**取得跟隨者TOP10 (GET /api/followships/top)**
-計算關聯資料數
-排序
**編輯自己所有的資料 (PUT /api/users/:id)**
-濾掉password

B33 (透過sequelize優化資料處理)

---

controllers/user-controller.js

優化userController.getUserLikes，直接從資料庫進行排序。

feat: modify order by likedDate

---

controllers/admin-controller.js
controllers/tweet-controller.js
controllers/user-controller.js

- dayjs顯示的相對時間中文化
- 管理者可以看見站內所有的使用者 (GET /api/admin/users) 撈關聯資料數由right outer join改為inner join

相對時間中文化及bug修復

---

controllers/user-controller.js

feat: GET api/followships/top API select top 10

---

controllers/tweet-controller.js

將createdAt的日期格式改為與UI設計一樣，讓前端可直接取用。
UI設計：
後端提供：

feat: modify createdAt date from getTweet
